# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPregunta', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('textAyuda', models.CharField(max_length=500)),
                ('minvalue', models.IntegerField(null=True)),
                ('maxvalue', models.IntegerField(null=True)),
                ('salto', models.CharField(max_length=1000, null=True)),
                ('next', models.IntegerField(null=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipopregunta', models.CharField(choices=[('1', 'Text'), ('2', 'Radio'), ('3', 'Check'), ('4', 'Date'), ('5', 'canvas'), ('6', 'foto'), ('7', 'audio')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tipoVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipovariable', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='valuesPreguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_id', models.IntegerField()),
                ('descripcion_valor', models.CharField(max_length=100)),
                ('numeroPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Pregunta')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tipovariable',
            unique_together=set([('id_tipovariable', 'descripcion')]),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipoPregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.TipoPregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipovariable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encuestas.tipoVariable'),
        ),
    ]
